apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=91fb6c73fd6e988c12bd2b50fb05d0d353db1a16
  - https://github.com/redhat-appstudio/integration-service/config/snapshotgc?ref=91fb6c73fd6e988c12bd2b50fb05d0d353db1a16
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service
    newTag: on-pr-7ea3fb1f9faadccfe04e5de5fd8272f4614dc5ff
configMapGenerator:
  - name: console-url
    literals:
      - CONSOLE_URL=""
      - CONSOLE_URL_TASKLOG=""
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
components:
  - ../rh-certs
