apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=b37833f64c8017c942ba95ca648d3b880b39af62
  - https://github.com/redhat-appstudio/integration-service/config/snapshotgc?ref=b37833f64c8017c942ba95ca648d3b880b39af62
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service
    newTag: on-pr-b982c0b143ac086c776873e548503e8937fa16eb
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
