apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=c199d2673bc5c7dc9936798acce1ffd9bad6864b
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/djodha/integration-service
    newTag: test-reruns
namespace: integration-service
components:
  - ../k-components/manager-resources-patch
