apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=f81a3355e7e08defe5d2e5d245313c4777294244
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service
    newTag: integration-service:on-pr-e477d82da4f6821d4fa93f249a9ef3bb2a6218a7
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
