apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=16e419239e99ae9c826be5735eba10e184f87019
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service
    newTag: integration-service:on-pr-9603c9fe507a9c010e87c43c4ecc6d7e83c9adac
namespace: integration-service
components:
  - ../k-components/manager-resources-patch
