resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/hongweiliu17/integration-service/config/default?ref=057886f8237c9c48436e3107f286603308d69534
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-appstudio/pull-request-builds
    newTag: integration-service-057886f8237c9c48436e3107f286603308d69534
namespace: integration-service
patches:
  - path: ./manager_resources_patch.yaml
