resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/dheerajodha/integration-service/config/default?ref=e36a25ec29686d57ef804871ae375b901cf6d449
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-appstudio/pull-request-builds
    newTag: integration-service-e36a25ec29686d57ef804871ae375b901cf6d449
namespace: integration-service
patches:
  - path: ./manager_resources_patch.yaml
